// InitialBoard.ts
import { SquareType } from "./Board";

const InitialBoard: SquareType[][] = [
    // Initial setup for a chess game
    [
        { piece: { type: "R", color: "black" }, highlighted: false },
        { piece: { type: "N", color: "black" }, highlighted: false },
        { piece: { type: "B", color: "black" }, highlighted: false },
        { piece: { type: "Q", color: "black" }, highlighted: false },
        { piece: { type: "K", color: "black" }, highlighted: false },
        { piece: { type: "B", color: "black" }, highlighted: false },
        { piece: { type: "N", color: "black" }, highlighted: false },
        { piece: { type: "R", color: "black" }, highlighted: false },
    ],
    [
        { piece: { type: "P", color: "black" }, highlighted: false },
        { piece: { type: "P", color: "black" }, highlighted: false },
        { piece: { type: "P", color: "black" }, highlighted: false },
        { piece: { type: "P", color: "black" }, highlighted: false },
        { piece: { type: "P", color: "black" }, highlighted: false },
        { piece: { type: "P", color: "black" }, highlighted: false },
        { piece: { type: "P", color: "black" }, highlighted: false },
        { piece: { type: "P", color: "black" }, highlighted: false },
    ],
    [
        { piece: { type: "P", color: "white" }, highlighted: false },
        { piece: { type: "P", color: "black" }, highlighted: false },
        { highlighted: false },
        { highlighted: false },
        { highlighted: false },
        { highlighted: false },
        { highlighted: false },
        { piece: { type: "P", color: "white" }, highlighted: false },
    ],
    [
        { highlighted: false },
        { highlighted: false },
        { highlighted: false },
        { highlighted: false },
        { highlighted: false },
        { highlighted: false },
        { highlighted: false },
        { highlighted: false },
    ],
    [
        { highlighted: false },
        { piece: { type: "P", color: "black" }, highlighted: false },
        { highlighted: false },
        { highlighted: false },
        { piece: { type: "R", color: "white" }, highlighted: false },
        { highlighted: false },
        { highlighted: false },
        { highlighted: false },
    ],
    [
        { piece: { type: "P", color: "black" }, highlighted: false },
        { highlighted: false },
        { highlighted: false },
        { highlighted: false },
        { piece: { type: "P", color: "black" }, highlighted: false },
        { highlighted: false },
        { highlighted: false },
        { piece: { type: "P", color: "black" }, highlighted: false },
    ],
    [
        { piece: { type: "P", color: "white" }, highlighted: false },
        { piece: { type: "P", color: "white" }, highlighted: false },
        { piece: { type: "P", color: "white" }, highlighted: false },
        { piece: { type: "P", color: "white" }, highlighted: false },
        { piece: { type: "P", color: "white" }, highlighted: false },
        { piece: { type: "P", color: "white" }, highlighted: false },
        { piece: { type: "P", color: "white" }, highlighted: false },
        { piece: { type: "P", color: "white" }, highlighted: false },
    ],
    [
        { piece: { type: "R", color: "white" }, highlighted: false },
        { piece: { type: "N", color: "white" }, highlighted: false },
        { piece: { type: "B", color: "white" }, highlighted: false },
        { piece: { type: "Q", color: "white" }, highlighted: false },
        { piece: { type: "K", color: "white" }, highlighted: false },
        { piece: { type: "B", color: "white" }, highlighted: false },
        { piece: { type: "N", color: "white" }, highlighted: false },
        { piece: { type: "R", color: "white" }, highlighted: false },
    ],
];

export default InitialBoard;
